[tool.mypy]
files = ["sample"]
disallow_untyped_defs = "True"
ignore_missing_imports = "True"
show_error_codes = "True"
warn_redundant_casts = "True"
warn_unused_configs = "True"
warn_unused_ignores = "True"
allow_redefinition = "True"
follow_imports = "silent"
follow_imports_for_stubs = "True"
exclude = []

# TODO: Fix typing for these modules
[[tool.mypy.overrides]]
module = [
]
ignore_errors = "True"


[[tool.mypy.overrides]]
module = [
]
ignore_errors = "False"
